# Problem 2
# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def run
  sum_of_fibs_up_to(4_000_000)
end

def sum_of_fibs_up_to(max)
  n1, n2 = 1, 1
  sum = 0

  while sum < max
    next_fib = n1 + n2
    sum += next_fib if next_fib.even?
    n1, n2 = n2, next_fib
  end
  
  sum
end

if __FILE__ == $0 
  puts run
 # puts fibs_up_to(90)  
end
